
- name: Create /app directory
  ansible.builtin.file:
    path: /app
    state: directory
    owner: '{{ server_user }}'
    group: '{{ server_user }}'
    mode: '0755'
  become: true

- name: Copy files app to target machine
  ansible.builtin.copy:
    src: "./roles/app/files/"
    dest: "/app/"
    owner: '{{ server_user }}'
    group: '{{ server_user }}'
  become: true


- name: Copy .env file to application directory
  ansible.builtin.copy:
    src: ./roles/app/templates/.env.j2
    dest: /app/.env
    owner: root
    group: root
    mode: '0644'

- name: Create systemd service file for app
  ansible.builtin.template:
    src: ./roles/app/templates/app.service.j2
    dest: /etc/systemd/system/app.service
    owner: root
    group: root
    mode: '0644'
  notify: Reload systemd

- name: Ensure app service is started and enabled
  ansible.builtin.service:
    name: app
    state: started
    enabled: yes
