- name: install packages
  ansible.builtin.apt:
    name:
          - curl
          - gnupg2
          - software-properties-common
          - apt-transport-https
          - lsb-release
          - ca-certificates
          - python3-dev
          - python3-pip
          - libpq-dev
  become: true
  
- name: install psycopg2 via pip
  ansible.builtin.pip:
    name: psycopg2-binary
    executable: pip3
    state: present

